game1 = input("Game sekarang =")
game2 = input("Game dulu =")
musuh = input("Musuh/Proplayer di game =")
gelar = input("Gelar/Peringkat musuh di game =")
nama_match = input("Nama matchnya =")

print("Bapak gue main",game1)
print(">pas main ketemu",musuh)
print("Dia",gelar,"di game ini")
print(">Bapak gue ngalahin dia")
print(">waktu bapak gue tanding, disiarkan Live di Twitch")
print(">ditonton ribuan orang")
print(">bapak gue berhasil ngalahin")
print(">para fans nya ngambek")
print(">mereka nuduh nuduh bapak gue curang")
print(">mereka ngereport massal akun bapak gue")
print(">akun bapak gue ke ban 10 tahun)")
print("Sumpah gue gak terima..")
print("mentang mentang public figure bisa")
print("seenaknya blokir akun orang...")
print("")
print("FYI: Bapak gw mantan pemain",game2,"yang sekarang dah pensiun.")
print("Terus gw tunjukin app",game2)
print("yang hampir mirip seperti",game2,". Akhirnya ketagihan")
print("main",nama_match," Match sampe ketemu para pro player.")
print("")
print("nah, kebetulan aja bapak gue ketemu dengan pro player yang lagi ngestream di twitch trus yang nonton fans garis keras semua")
print("(bapak gue nggak tau apa-apa karena nggak pake cheat)")
print("")
print("Sekarang bapak gue bingung mau main kaya gimana karna akunnya ke ban")